# Generated by Django 3.2.9 on 2021-11-19 11:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Vendor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vendor', models.CharField(max_length=50, verbose_name='Производитель')),
            ],
        ),
        migrations.CreateModel(
            name='Schematic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model', models.CharField(max_length=50, verbose_name='Модель')),
                ('file', models.FileField(upload_to='upload/schematic', verbose_name='Файл')),
                ('manufactured', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='sc.vendor', verbose_name='Производитель')),
            ],
        ),
    ]
