# Generated by Django 3.2.9 on 2021-11-26 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sc', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='schematic',
            options={'ordering': ['id'], 'verbose_name': 'Схемы', 'verbose_name_plural': 'Схемы'},
        ),
        migrations.AlterModelOptions(
            name='vendor',
            options={'ordering': ['id'], 'verbose_name': 'Производители', 'verbose_name_plural': 'Производители'},
        ),
        migrations.AlterField(
            model_name='schematic',
            name='file',
            field=models.FileField(upload_to='schematic/', verbose_name='Файл'),
        ),
    ]
