# Generated by Django 3.2.9 on 2021-12-07 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sc', '0003_auto_20211207_1002'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='service_list',
            field=models.ManyToManyField(blank=True, to='sc.Service_list', verbose_name='Оказанные услуги'),
        ),
    ]
