# Generated by Django 4.0 on 2021-12-20 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sc', '0004_alter_service_service_list'),
    ]

    operations = [
        migrations.AddField(
            model_name='stage',
            name='bs_color',
            field=models.CharField(default='success', max_length=50, verbose_name='Цвет по категориям боотстрап'),
        ),
        migrations.AlterField(
            model_name='client',
            name='phone',
            field=models.IntegerField(verbose_name='Номер телефона'),
        ),
    ]
